use_frameworks!

target 'GRFramework_Example' do
  pod 'GRFramework', :path => '../'

  target 'GRFramework_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
  pod 'FBSnapshotTestCase'
  pod 'Nimble-Snapshots'
  end
end
